<a href="https://colab.research.google.com/github/oswram19/etl-data-pipeline/blob/main/notebooks/asegurador.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import re

In [3]:
url ="https://raw.githubusercontent.com/oswram19/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"
df = pd.read_csv(url)

df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [4]:

#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

In [5]:
#limpieza de datos
aseguradoras = df.copy()
aseguradoras["nombre"] = aseguradoras["nombre"].str.title()
aseguradoras["pais"] = aseguradoras["pais"].str.title()

map_rating = {
    "alto": "Alto",
    "medio": "Medio",
    "bajo": "Bajo"
}

aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].str.lower().map(map_rating)
aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].fillna("No especificado")
aseguradoras["pais"] = aseguradoras["pais"].fillna("No especificado")

In [6]:
# Separar datos validos y rechazados
validos = aseguradoras[
    aseguradoras['nombre'].notna() &
    aseguradoras['pais'].notna() &
    aseguradoras['rating_riesgo'].notna()
].copy()

rechazados = aseguradoras[
    aseguradoras['nombre'].isna() |
    aseguradoras['pais'].isna()|
    aseguradoras['rating_riesgo'].isna()
].copy()

In [7]:
#Motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['pais']):
        motivos.append("pais_vacio")

    if pd.isna(row['pais']):
        motivos.append("rating_riesgo_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [8]:
validos.to_csv("aseguradoras_curated.csv", index=False)
rechazados.to_csv("aseguradoras_rejects.csv", index=False)

In [9]:
from sqlalchemy import create_engine

engine = create_engine(
"postgresql://etl_seguros_gs5p_user:mlggyX4FmZphFrbO1p9v1Amxiu2bIkMO@dpg-d6qu59fkijhs73bcuo0g-a.oregon-postgres.render.com/etl_seguros_gs5p"
)

In [10]:
validos.to_sql(
    'aseguradoras_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'aseguradoras_rejects',
    engine,
    if_exists='append',
    index=False
)

0